// <auto-generated />
using CityInfo.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.Api.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    partial class CityInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CityInfo.Api.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descreption")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descreption = "this is tehran",
                            Name = "tehran"
                        },
                        new
                        {
                            Id = 2,
                            Descreption = "this is shiraz",
                            Name = "shiraz"
                        },
                        new
                        {
                            Id = 3,
                            Descreption = "this is gheshm",
                            Name = "gheshm"
                        });
                });

            modelBuilder.Entity("CityInfo.Api.Entities.PointOfIntrest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descreption")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("pointOfIntrests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Descreption = "this is tange washi",
                            Name = "tange washi"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Descreption = "this is tange washi",
                            Name = "kakh sad abad"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Descreption = "this is tange masged nasir ",
                            Name = "masged nasir"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Descreption = "this is aramgah sadi",
                            Name = "aramgah saddi"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Descreption = "this gheshm abad ",
                            Name = "gheshm abad"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Descreption = "this is gheshmak",
                            Name = "geshmak"
                        });
                });

            modelBuilder.Entity("CityInfo.Api.Entities.PointOfIntrest", b =>
                {
                    b.HasOne("CityInfo.Api.Entities.City", "city")
                        .WithMany("PointOfIntrest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("CityInfo.Api.Entities.City", b =>
                {
                    b.Navigation("PointOfIntrest");
                });
#pragma warning restore 612, 618
        }
    }
}
